name: CI ManyLinux

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # conda install --file conda_requirements.txt
        pip install -r requirements.txt
        pip uninstall bed-reader --yes
        pip uninstall pysnptools --yes
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bed-reader
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pysnptools
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38m'
        build-requirements: 'cython numpy'

    - name: Save Wheels
        uses: actions/upload-artifact@v2
        with:
        name: wheels
        path: dist/*.whl
